### Product & User Funnel Analytics - Data Cleaning

In [27]:
# Importing python Libraries for analysis
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Reading csv data in pandas

df = pd.read_csv("d2c_marketing_funnel_data.csv")
df.head()

,user_id,session_id,date,month,channel,campaign_type,device,user_type,region,visited_website,viewed_product,added_to_cart,checkout_started,purchase_completed,discount_applied,order_value,revenue
0,221958,1,8/16/2025,2025-08,Organic,New Launch,Mobile,New,Metro,Yes,No,No,No,No,No,499.00,0.000
1,771155,2,12/16/2025,2025-12,Organic,Influencer,Mobile,New,Non-Metro,Yes,Yes,Yes,No,No,No,499.00,0.000
2,231932,3,7/17/2025,2025-07,Organic,Influencer,Mobile,New,Non-Metro,Yes,Yes,No,No,No,No,499.00,0.000
3,465838,4,7/4/2025,2025-07,Paid Ads,Discount,Mobile,Returning,Metro,Yes,Yes,Yes,Yes,Yes,Yes,2000.95,1800.855
4,359178,5,8/10/2025,2025-08,Paid Ads,Influencer,Mobile,Returning,Non-Metro,Yes,No,No,No,No,No,499.00,0.000

In [9]:
# DataFrame Summary

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   user_id             120000 non-null  int64
 1   session_id          120000 non-null  int64
 2   date                120000 non-null  object
 3   month               120000 non-null  object
 4   channel             120000 non-null  object
 5   campaign_type       120000 non-null  object
 6   device              120000 non-null  object
 7   user_type           120000 non-null  object
 8   region              120000 non-null  object
 9   visited_website     120000 non-null  object
 10  viewed_product      120000 non-null  object
 11  added_to_cart       120000 non-null  object
 12  checkout_started    120000 non-null  object
 13  purchase_completed  120000 non-null  object
 14  discount_applied    120000 non-null  object
 15  order_value         120000 non-null  float64
 16  revenue             120000 non-null  float64
dtypes: float64(2), int64(2), object(13)
memory usage: 15.6+ MB

In [11]:
#statistical summary of a DataFrame 

df.describe().round()

        user_id  session_id  order_value   revenue
count  120000.0    120000.0     120000.0  120000.0
mean   550416.0     60000.0        615.0     142.0
std    260167.0     34641.0        456.0     545.0
min    100005.0         1.0        499.0       0.0
25%    325121.0     30001.0        499.0       0.0
50%    551419.0     60000.0        499.0       0.0
75%    775713.0     90000.0        499.0       0.0
max    999998.0    120000.0       4741.0    4741.0

In [12]:
# Checking for Null Values

df.isnull().sum()

user_id               0
session_id            0
date                  0
month                 0
channel               0
campaign_type         0
device                0
user_type             0
region                0
visited_website       0
viewed_product        0
added_to_cart         0
checkout_started      0
purchase_completed    0
discount_applied      0
order_value           0
revenue               0
dtype: int64

In [14]:
# Checking for Duplicate values

df.duplicated().sum()

np.int64(0)

In [15]:
# Checking for Data inconsistensies

df["channel"].unique()

array(['Organic', 'Paid Ads', 'Social', 'Email'], dtype=object)

In [16]:
df["campaign_type"].unique()

array(['New Launch', 'Influencer', 'Discount'], dtype=object)

In [17]:
df["device"].unique()

array(['Mobile', 'Desktop'], dtype=object)

In [18]:
df["user_type"].unique()

array(['New', 'Returning'], dtype=object)

In [19]:
df["region"].unique()

array(['Metro', 'Non-Metro'], dtype=object)

In [22]:
user_cols = ["visited_website","viewed_product","added_to_cart","checkout_started","purchase_completed","discount_applied"]

for col in user_cols:
    print(col)
    print(df[col].unique())

visited_website
['Yes']
viewed_product
['No' 'Yes']
added_to_cart
['No' 'Yes']
checkout_started
['No' 'Yes']
purchase_completed
['No' 'Yes']
discount_applied
['No' 'Yes']

In [25]:
# Fixing Column datatypes

df.dtypes

user_id                        int64
session_id                     int64
date                  datetime64[ns]
month                         object
channel                       object
campaign_type                 object
device                        object
user_type                     object
region                        object
visited_website               object
viewed_product                object
added_to_cart                 object
checkout_started              object
purchase_completed            object
discount_applied              object
order_value                  float64
revenue                      float64
dtype: object

In [24]:
df["date"] = pd.to_datetime(df["date"])

In [26]:
# Feature engineering

df[user_cols] = df[user_cols].replace({
    "Yes":1,
     "No":0})

df[user_cols]

C:\Users\HarishNew\AppData\Local\Temp\ipykernel_10936\2354880065.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[user_cols] = df[user_cols].replace({

,visited_website,viewed_product,added_to_cart,checkout_started,purchase_completed,discount_applied
0,1,0,0,0,0,0
1,1,1,1,0,0,0
2,1,1,0,0,0,0
3,1,1,1,1,1,1
4,1,0,0,0,0,0
...,...,...,...,...,...,...
119995,1,1,0,0,0,0
119996,1,1,1,1,1,0
119997,1,1,0,0,0,0
119998,1,1,0,0,0,0
119999,1,1,1,0,0,0

In [38]:
# Find sessions that added to cart without viewing a product:

df[
    (df["added_to_cart"] == 1) &
    (df["viewed_product"] == 0)
]

Empty DataFrame
Columns: [user_id, session_id, date, month, channel, campaign_type, device, user_type, region, visited_website, viewed_product, added_to_cart, checkout_started, purchase_completed, discount_applied, order_value, revenue, funnel_stage, funnel_dropoff_stage]
Index: []

In [39]:
# Finding sessions with checkout without cart:

df[
    (df["checkout_started"] == 1) &
    (df["added_to_cart"] == 0)
]

Empty DataFrame
Columns: [user_id, session_id, date, month, channel, campaign_type, device, user_type, region, visited_website, viewed_product, added_to_cart, checkout_started, purchase_completed, discount_applied, order_value, revenue, funnel_stage, funnel_dropoff_stage]
Index: []

In [40]:
# Check purchase without checkout:

df[
    (df["purchase_completed"] == 1) &
    (df["checkout_started"] == 0)
]

Empty DataFrame
Columns: [user_id, session_id, date, month, channel, campaign_type, device, user_type, region, visited_website, viewed_product, added_to_cart, checkout_started, purchase_completed, discount_applied, order_value, revenue, funnel_stage, funnel_dropoff_stage]
Index: []

In [34]:
import numpy as np

conditions = [
    df["purchase_completed"] == 1,
    df["checkout_started"] == 1,
    df["added_to_cart"] == 1,
    df["viewed_product"] == 1,
    df["visited_website"] == 1
]

choices = [
    "Purchased",
    "Checkout Started",
    "Added to Cart",
    "Viewed Product",
    "Visited Website"
]

df["funnel_stage"] = np.select(
    conditions,
    choices,
    default="No Activity"
)

df["funnel_stage"].unique()

array(['Visited Website', 'Added to Cart', 'Viewed Product', 'Purchased',
       'Checkout Started'], dtype=object)

In [33]:
df.head()

,user_id,session_id,date,month,channel,campaign_type,device,user_type,region,visited_website,viewed_product,added_to_cart,checkout_started,purchase_completed,discount_applied,order_value,revenue,funnel_stage
0,221958,1,2025-08-16,2025-08,Organic,New Launch,Mobile,New,Metro,1,0,0,0,0,0,499.00,0.000,Visited Website
1,771155,2,2025-12-16,2025-12,Organic,Influencer,Mobile,New,Non-Metro,1,1,1,0,0,0,499.00,0.000,Added to Cart
2,231932,3,2025-07-17,2025-07,Organic,Influencer,Mobile,New,Non-Metro,1,1,0,0,0,0,499.00,0.000,Viewed Product
3,465838,4,2025-07-04,2025-07,Paid Ads,Discount,Mobile,Returning,Metro,1,1,1,1,1,1,2000.95,1800.855,Purchased
4,359178,5,2025-08-10,2025-08,Paid Ads,Influencer,Mobile,Returning,Non-Metro,1,0,0,0,0,0,499.00,0.000,Visited Website

In [37]:
import numpy as np

conditions = [ 
    df["visited_website"] == 0,
    df["viewed_product"] == 0,
    df["added_to_cart"] == 0,
    df["checkout_started"] == 0,
    df["purchase_completed"] == 0
]

choices = [
    "Website Visit",
    "Product View",
    "Add to Cart",
    "Checkout",
    "Purchase"
]

df["funnel_dropoff_stage"] = np.select(
    conditions,
    choices,
    default="No Drop-off"
)

df.head()

,user_id,session_id,date,month,channel,campaign_type,device,user_type,region,visited_website,viewed_product,added_to_cart,checkout_started,purchase_completed,discount_applied,order_value,revenue,funnel_stage,funnel_dropoff_stage
0,221958,1,2025-08-16,2025-08,Organic,New Launch,Mobile,New,Metro,1,0,0,0,0,0,499.00,0.000,Visited Website,Product View
1,771155,2,2025-12-16,2025-12,Organic,Influencer,Mobile,New,Non-Metro,1,1,1,0,0,0,499.00,0.000,Added to Cart,Checkout
2,231932,3,2025-07-17,2025-07,Organic,Influencer,Mobile,New,Non-Metro,1,1,0,0,0,0,499.00,0.000,Viewed Product,Add to Cart
3,465838,4,2025-07-04,2025-07,Paid Ads,Discount,Mobile,Returning,Metro,1,1,1,1,1,1,2000.95,1800.855,Purchased,No Drop-off
4,359178,5,2025-08-10,2025-08,Paid Ads,Influencer,Mobile,Returning,Non-Metro,1,0,0,0,0,0,499.00,0.000,Visited Website,Product View

In [48]:
df["month_name"] = df["date"].dt.month_name()

In [42]:
stage_mapping = {
    "Visited Website": 1,
    "Viewed Product": 2,
    "Added to Cart": 3,
    "Checkout Started": 4,
    "Purchased": 5
}

df["funnel_depth"] = df["funnel_stage"].map(stage_mapping)

In [50]:
df.tail()

,user_id,session_id,date,month,channel,campaign_type,device,user_type,region,visited_website,...,added_to_cart,checkout_started,purchase_completed,discount_applied,order_value,revenue,funnel_stage,funnel_dropoff_stage,funnel_depth,month_name
119995,969282,119996,2025-07-07,2025-07,Paid Ads,Influencer,Mobile,Returning,Non-Metro,1,...,0,0,0,0,499.00,0.00,Viewed Product,Add to Cart,2,July
119996,731196,119997,2025-12-15,2025-12,Paid Ads,Discount,Mobile,New,Non-Metro,1,...,1,1,1,0,2735.11,2735.11,Purchased,No Drop-off,5,December
119997,784144,119998,2025-12-26,2025-12,Social,Discount,Desktop,New,Metro,1,...,0,0,0,0,499.00,0.00,Viewed Product,Add to Cart,2,December
119998,946736,119999,2025-09-05,2025-09,Email,Influencer,Mobile,New,Non-Metro,1,...,0,0,0,0,499.00,0.00,Viewed Product,Add to Cart,2,September
119999,407177,120000,2025-08-13,2025-08,Social,New Launch,Mobile,New,Non-Metro,1,...,1,0,0,0,499.00,0.00,Added to Cart,Checkout,3,August

In [51]:
# cart_abandoned

df["cart_abandoned"] = (
    (df["added_to_cart"] == 1) &
    (df["checkout_started"] == 0)
).astype(int)

In [52]:
# checkout_abandoned

df["checkout_abandoned"] = (
    (df["checkout_started"] == 1) &
    (df["purchase_completed"] == 0)
).astype(int)

In [53]:
# high_intent_session

df["high_intent_session"] = (
    (df["added_to_cart"] == 1) |
    (df["checkout_started"] == 1) |
    (df["purchase_completed"] == 1)
).astype(int)

In [63]:
df[["visited_website","viewed_product","added_to_cart","checkout_started","purchase_completed","discount_applied",
    "funnel_stage","funnel_dropoff_stage","funnel_depth","cart_abandoned","checkout_abandoned","high_intent_session"]].tail(10)

,visited_website,viewed_product,added_to_cart,checkout_started,purchase_completed,discount_applied,funnel_stage,funnel_dropoff_stage,funnel_depth,cart_abandoned,checkout_abandoned,high_intent_session
119990,1,1,1,1,1,1,Purchased,No Drop-off,5,0,0,1
119991,1,1,1,0,0,0,Added to Cart,Checkout,3,1,0,1
119992,1,1,0,0,0,0,Viewed Product,Add to Cart,2,0,0,0
119993,1,0,0,0,0,0,Visited Website,Product View,1,0,0,0
119994,1,1,1,1,1,1,Purchased,No Drop-off,5,0,0,1
119995,1,1,0,0,0,0,Viewed Product,Add to Cart,2,0,0,0
119996,1,1,1,1,1,0,Purchased,No Drop-off,5,0,0,1
119997,1,1,0,0,0,0,Viewed Product,Add to Cart,2,0,0,0
119998,1,1,0,0,0,0,Viewed Product,Add to Cart,2,0,0,0
119999,1,1,1,0,0,0,Added to Cart,Checkout,3,1,0,1

In [64]:
## Save to the current working directory

df.to_csv('Data/Processed/final_d2c_marketing_funnel_data.csv', index=False)